### PR TITLE
Convert everything to Javascript

### PR DESCRIPTION
**Pull request by cmnord**
Coffeescript is dead -- hopefully this will make hackbot easier for new devs to work on!

### CODE REVIEW

**Comment by cmnord** [comment]
lol I should have done this in many commits but /shrug

**Comment by cmnord** [comment]
bump @Justinyu1618 thoughts? hopefully this will make hackbot more maintainable.

**Comment by cmnord** [comment]
bump bump @Justinyu1618 @kyeb

**Comment by kyeb** [comment]
How tested is the transition right now?

**Comment by cmnord** [comment]
I tested each script manually myself and they worked. I used the [decaffeinate](https://github.com/decaffeinate/decaffeinate) package -- it wasn't a manual translation.

**Comment by cmnord** [comment]
If you look through the commits you'll see that most are linting or incorporating suggestions from decaffeinate.

**Pull request merged**
